apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapUsers: |
    - userarn: arn:aws:iam::582512839761:user/Capston
      username: Capston
      groups:
        - system:masters
  mapRoles: |
    - rolearn: arn:aws:iam::582512839761:role/devops-capstone-nodes-NodeInstanceRole-VF8CQ841IA0N
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:bootstrappers
        - system:nodes
