apiVersion: apps/v1
kind: Deployment
metadata:
  name: capstone-app-dep
  labels:
    app: capstone-app-dep
spec:
  replicas: 2
  selector:
    matchLabels:
      app: capstone-app-dep
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: capstone-app-dep
    spec:
      containers:
        - image: fzaben/capstone-app:latest
          name: capstone-app-dep
          ports:
            - containerPort: 80
              name: http-server
      imagePullSecrets:
        - name: ecr-secret
